I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 119, in script
    show kieran shy with fade_texto
  File "game/script.rpy", line 119, in <module>
    show kieran shy with fade_texto
NameError: name 'fase' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 119, in script
    show kieran shy with fade_texto
  File "C:\Users\Aura\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 1370, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Aura\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Aura\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 119, in <module>
    show kieran shy with fade_texto
NameError: name 'fase' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
The Last Day Forever 1.0
Fri Aug 29 12:41:08 2025
